### ISSUE TITLE
Failed to add node

### ISSUE THREAD

**Issue by kamikazechaser** [fireworq/fireworqonsole#291]
I am trying to add a node to the fireworqonsole. However, the API returns a 502 error.

**Steps to reproduce**

1. Run `fireworq/fireworq:latest` on port 8080 (port exposed to localhost)
2. Confirm `fireworq` is up and running with `curl localhost:8080/version` which returns `Fireworq 1.4.0+421eb55`
3. Run `fireworq/fireworqconsole:latest` on port 8888 (port exposed to localhost)
4. Attempt to add a node with string as `localhost:8080` (tried `http://localhost:8080` too)

I also attempted to reproduce the API request on a REST client, output is below:

```bash
> PUT /api/node/localhost:8080 HTTP/1.1
> Host: localhost:8888
> User-Agent: insomnia/2020.4.2
> Accept: */*
> Content-Length: 0


< HTTP/1.1 502 Bad Gateway
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 22 Jan 2021 09:00:22 GMT
< Content-Length: 12
```

Proxying is failing here => https://github.com/fireworq/fireworqonsole/blob/master/api.go#L84.

**Comment by tarao** [comment]
If you are running fireworqonsole in a docker container, then the host to add must be Docker host resolvable inside the container (`172.17.0.1` on Linux default networking, or hostname `host.docker.internal` on macOS) because `localhost` means the container in which fireworqonsole is running.

**Comment by kamikazechaser** [comment]
Thanks its working!
